### PR TITLE
feat: watch later & likes

### PR DESCRIPTION
**Pull request by himadri2110**
- Add/remove a video from Watch later
- Like/dislike video

### CODE REVIEW

**Review by poornima-alugubelly — APPROVED** [review]
Good use of abstraction 👍

**Comment by poornima-alugubelly** [comment]
Just a suggestion if the user is not logged in and clicks add to watch later then redirect him to login page , currently nothing is happening

**Comment by himadri2110** [comment]
> Just a suggestion if the user is not logged in and clicks add to watch later then redirect him to login page , currently nothing is happening

Missed checking this. Thanks for pointing it out. Fixed!

**Review by msdeshmukh009 — APPROVED** [review]
The code looks clean and everything looks good to me. Except the user should be able to add video into watch later from the single video page as well. So, you might as well add that functionality.

**Review by manojasarsa — APPROVED** [review]
Code is clean and self-explanatory.
GTG!

**Comment by himadri2110** [comment]
> The code looks clean and everything looks good to me. Except the user should be able to add video into watch later from the single video page as well. So, you might as well add that functionality.

Done, thanks for pointing it out.

**Pull request merged**
